[package]
name = "thalia"
version = "0.0.1"
authors = ["Damian Monea"]
edition = "2021"
description = "A quick and straight forward AI library written in Rust."
license = "MIT"

[dependencies]
rand = "0.8.5"
rayon = "1.8.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3